spring:
  application:
    name: stockbasket

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-ms: ${JWT_ACCESS_TOKEN_VALIDITY_MS}

openai:
  api-key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL}

claude:
  api-key: ${CLAUDE_API_KEY}
  model: ${CLAUDE_MODEL}

llm:
  gemini:
    api-key: ${GEMINI_API_KEY}
    model: ${GEMINI_MODEL}
